### ISSUE TITLE
Migrate into gitlab?

### ISSUE THREAD

**Issue by seamuslee001** [adixon/ca.civicrm.moneris#9]
Should we move this extension into git lab? I note JMA has been kind of running our own fork of this for a while and I think @mlutfy has also been doing similar. I'm not sure if there is a canonical source or not but is someone able to advise what the status of this?

**Comment by adixon** [comment]
I'm game! I don't have many permissions in gitlab, but tell me if I can help.

I do have one or two clients still using this for one-time payments and it kind of amazes me that their api still works, but I'm sure there are lots of improvements that could be done.

**Comment by JoeMurray** [comment]
Good suggestion, @seamuslee001 . It might be a good time to review what is on different forks and either retain branches where people desire or if agreed, move to merging into a more general one.

**Comment by mlutfy** [comment]
My colleague @samuelsov has a branch here, for Vault integration (for recurring payments, I think, ymmv):  
https://github.com/coopsymbiotic/ca.civicrm.moneris/tree/vault

If you would like to migrate this extension to Gitlab, the process is documented here:  
https://lab.civicrm.org/extensions/extensions-directory/-/wikis/import-from-github

In short: import as a project in your personal space, then ping me so that I move it under `lab.civicrm.org/extensions`

**Comment by adixon** [comment]
Better late than never, this is done.

https://lab.civicrm.org/AlanDixon/moneris

**Comment by JoeMurray** [comment]
@seamuslee001 could you ensure that any generic stuff on branches we may have on our repo get migrated? Thx
